# Generated by Django 3.2.9 on 2021-12-08 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=50)),
                ('price', models.TextField(max_length=50)),
                ('quantity', models.TextField(max_length=50)),
                ('discount', models.TextField(max_length=50)),
                ('description', models.TextField(max_length=200, null=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
