# Generated by Django 3.2.9 on 2021-12-09 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_alter_products_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='products',
        ),
    ]
