# Generated by Django 3.2.9 on 2021-12-09 03:27

import adminpanel.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0005_delete_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('price', models.CharField(max_length=20)),
                ('description', models.TextField(max_length=500, null=True)),
                ('discount', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, null=True, upload_to=adminpanel.models.filepath)),
            ],
        ),
    ]
