# Generated by Django 3.2.9 on 2021-12-09 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='discount',
        ),
    ]
