# Generated by Django 3.2.9 on 2021-12-13 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0009_auto_20211213_1121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagry',
            name='category',
        ),
    ]
