# Generated by Django 3.2.9 on 2021-12-13 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0012_item_categry'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='categry',
        ),
        migrations.AddField(
            model_name='catagry',
            name='category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.item'),
        ),
        migrations.AddField(
            model_name='item',
            name='category',
            field=models.CharField(default=True, max_length=20),
        ),
    ]
