# Generated by Django 3.2.9 on 2021-12-16 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_auto_20211213_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=models.IntegerField(max_length=20),
        ),
    ]
