# Generated by Django 3.2.9 on 2021-12-20 05:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_alter_item_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catagry',
            name='category',
        ),
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
        migrations.AddField(
            model_name='item',
            name='categry',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='adminpanel.catagry'),
        ),
    ]
