# Generated by Django 3.2.9 on 2021-12-27 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_auto_20211220_0513'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='offerprice',
            field=models.IntegerField(default=True, max_length=20),
        ),
    ]
