# Generated by Django 3.2.9 on 2021-12-27 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_item_offerprice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='offerprice',
            field=models.IntegerField(default='Null', max_length=20),
        ),
    ]
