# Generated by Django 3.2.9 on 2021-12-27 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0018_alter_item_offerprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='catagry',
            name='discount',
            field=models.IntegerField(default=0),
        ),
    ]
