# Generated by Django 3.2.9 on 2021-12-06 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('email', models.EmailField(default='email@gmail.com', max_length=20)),
                ('number', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
    ]
