# Generated by Django 3.2.9 on 2021-12-06 10:39

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_rename_usersignup_create_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='usersignup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True, verbose_name=django.contrib.auth.models.User)),
                ('email', models.EmailField(default='email@gmail.com', max_length=20, unique=True)),
                ('number', models.CharField(max_length=14)),
                ('password', models.CharField(max_length=10)),
            ],
        ),
        migrations.DeleteModel(
            name='create_user',
        ),
    ]
