# Generated by Django 3.2.9 on 2021-12-06 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_usersignup_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='usersignup',
        ),
    ]
