# Generated by Django 3.2.9 on 2021-12-07 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_auto_20211207_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='email',
            field=models.CharField(default=True, max_length=50, unique=True),
        ),
    ]
