# Generated by Django 3.2.9 on 2021-12-08 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0021_auto_20211208_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounts',
            name='phone',
            field=models.BigIntegerField(),
        ),
    ]
