# Generated by Django 3.2.9 on 2021-12-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0028_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='totalprice',
            field=models.IntegerField(default=True),
        ),
    ]
