# Generated by Django 3.2.9 on 2021-12-21 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0030_address_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(default='pending', max_length=50)),
                ('total', models.IntegerField(default=True)),
                ('mode', models.CharField(default=True, max_length=20)),
                ('date_added', models.DateField(default=django.utils.timezone.now)),
                ('address', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to='app.address')),
                ('user', models.ForeignKey(default=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
