# Generated by Django 3.2.9 on 2021-12-21 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_auto_20211220_0513'),
        ('app', '0031_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='ordereditem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(default=True)),
                ('price', models.IntegerField(default=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.item')),
                
            ],
        ),
    ]
