# Generated by Django 3.2.9 on 2021-12-27 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0036_auto_20211222_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='offerprice',
            field=models.IntegerField(default=0),
        ),
    ]
