# Generated by Django 3.2.9 on 2021-12-27 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0038_auto_20211227_0944'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='offerprice',
        ),
    ]
