# Generated by Django 3.2.9 on 2021-12-28 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0040_cart_discountprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='discountprice',
        ),
    ]
