# Generated by Django 3.2.9 on 2021-12-28 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0041_remove_cart_discountprice'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='discountprice',
            field=models.IntegerField(default=0),
        ),
    ]
