# Generated by Django 3.2.9 on 2021-12-29 04:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminpanel', '0020_coupon'),
        ('app', '0042_cart_discountprice'),
    ]

    operations = [
        migrations.CreateModel(
            name='couponapplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('couponofferprice', models.IntegerField(default=0)),
                ('offerended', models.BooleanField(default=0)),
                ('appliedcoupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.coupon')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
