# Generated by Django 3.2.9 on 2022-01-02 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0043_couponapplied'),
    ]

    operations = [
        migrations.AddField(
            model_name='couponapplied',
            name='placed',
            field=models.BooleanField(default=0),
        ),
    ]
